### PR TITLE
Readme.md updated with LSApplicationQueriesSchemes for iOS

### PR DESCRIPTION
**Pull request by navneet-kumar**
This works perfectly in android however in iOS nothing happens after the call : https://github.com/navneet-kumar/MyClinic/blob/feature/iOS/src/components/Helpers.js#L161

I am using real iOS device with version 12.1.4

please help me figuring out the issue

### CODE REVIEW

**Comment by wumke** [comment]
I'm very busy at the moment, when I find the time I will test and let you know...
Do you perhaps have spaces in the number? (You can inspect the generated url value in the library project...)

**Comment by navneet-kumar** [comment]
@wumke Thank you very much for the quick response, NO i have tried with number without spaces too  issue still exists

**Comment by wumke** [comment]
Can you try adding the following native line in the appdelegate.m file to test?
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
 ...
  [[UIApplication sharedApplication] openURL:[NSURL URLWithString:[NSString stringWithFormat:@"tel:%@", @"0123456789"]]];
...
}
```
I tested this on a project with RN 0.57.8 on iPhone 7 with iOS 12.1.4 and the popup with the number is shown correctly to me, when I then press call it works as expected.

**Comment by wumke** [comment]
I've found this old thread: [https://stackoverflow.com/questions/35792681/how-to-open-phone-dialler-in-ios-9](https://stackoverflow.com/questions/35792681/how-to-open-phone-dialler-in-ios-9)
Is there a valid SIM card in your device?
Worked in my project without LSApplicationQueriesSchemes...

**Comment by navneet-kumar** [comment]
@wumke, Thanks a lot for your efforts, Yes my device has valid sim card. I have checked that post also.

I also tried to run my project directly from x code and put a breakpoint there but it never called the code and same for other functionalities but other functionalities are working. I think we can't really debug react native app as native apps .. :(

However Thanks for the pointer i'll check it and send you the response.

**Pull request merged**
